### PR TITLE
Flush memory as soon as we no longer need it.

### PR DESCRIPTION
**Pull request by ltratt**
This should reduce peak RAM usage and, since that makes a bit less work for the GC, it might improve performance a little bit too.

### CODE REVIEW

**Comment by ptersilie** [comment]
Looks good. Needs squashing? If so please do.

**Comment by ltratt** [comment]
Ah, I should actually kill the `collect()` diff, as when I tested, it made no discernible difference. Are you OK with me doing that?

**Comment by ptersilie** [comment]
Sure. Go ahead.

**Comment by ltratt** [comment]
Commit removed -- ready to merge!

**Review by ptersilie — APPROVED** [review]

**Pull request merged**
