### PR TITLE
Updated to recent grmtools changes

### PR DESCRIPTION
**Pull request by ptersilie**
This PR updates the experiment to the recent API changes made in grmtools.

What I wasn't sure about is if I also need to commit the new Cargo.lock file.

### CODE REVIEW

**Review by ltratt — APPROVED** [review]

**Comment by ltratt** [comment]
Looks good! You need to also `git rm java_parser.Cargo.lock` though, otherwise it'll cause weird failures in the build (since the `lock` file won't include the updated grmtools libraries you're now using). You can do that as a second commit if you want.

**Comment by ptersilie** [comment]
Shall I replace it with a new `Cargo.lock` file or just remove it? If I remove it, I also have to remove some lines from `build.sh`

**Comment by ltratt** [comment]
`build.sh` knows that the `.lock` file might not exist https://github.com/softdevteam/error_recovery_experiment/blob/master/runner/build.sh#L23 for just this reason, so rm'ing it is fine.

**Comment by ptersilie** [comment]
Wait, but that copies `java_parser.Cargo.lock` to `java_parser/Cargo.lock`, if the latter doesn't exist. Which won't work if I remove `java_parser.Cargo.lock`.

**Comment by ltratt** [comment]
Ooooooops! You're quite correct. Maybe I hallucinated this, or I changed it at some point. Anyway, if you change that line in `build.sh` to something like:

```sh
if [ -f java_parser.Cargo.lock && ! -f java_parser/Cargo.lock ]; then
```

it should hopefully do the right thing.

**Comment by ptersilie** [comment]
Okay, but if I remove `java_parser.Cargo.lock`, then this will never trigger anyways, so why not remove the whole block from `build.sh`?

**Comment by ptersilie** [comment]
Or is this for backwards compatibility reasons? What is the point of `java_parser.Cargo.lock` anyways?

**Comment by ltratt** [comment]
The `lock` file lets you build *exactly* the same binary I used to run the experiment.

**Comment by ptersilie** [comment]
Okay, so should I update it then or not? If we remove it then people can't build exactly the same binary as in the paper, right?

**Comment by ltratt** [comment]
I'm going to rerun the experiment, so I'll be generating a new lock file at some point. The one in the repo at the moment isn't important (and, besides, it never dies: in the paper I'll point them at a repository hash so they can get the old lock file for evermore).

**Comment by ptersilie** [comment]
Okay, I'll remove it then as discussed above.

**Comment by ptersilie** [comment]
Removed the lock, will squash if ok.

**Comment by ltratt** [comment]
Please squash.

**Comment by ptersilie** [comment]
Squashed!

**Pull request merged**
